/*
Test Automation (No submodules)

Testing GreetingsApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package automationtestwithsubmodules

import (
    "testing"
    // "github.com/stretchr/testify/assert"
    // "github.com/stretchr/testify/require"
    // automationtestwithsubmodules "github.com/konfig-dev/automation-test-submodule-go"
)

func Test_automationtestwithsubmodules_GreetingsApiService(t *testing.T) {

    // configuration := automationtestwithsubmodules.NewConfiguration()
    // configuration.SetHost("http://127.0.0.1:4010")
    /* 
    configuration.SetApiKey("SUPER_SECRET_KEY")
    client := automationtestwithsubmodules.NewAPIClient(configuration)
    */

    t.Run("Test GreetingsApiService Hello", func(t *testing.T) {
        /* TODO: ENG-1367 Fix parameter values for Go SDK generated tests
        request := client.GreetingsApi.Hello(
        )
        
        resp, httpRes, err := request.Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)
        */
    })

}